### ISSUE TITLE
suggestion: query string should sanitize tabs

### ISSUE THREAD

**Issue by dylbarne** [ehmad11/suiteql#5]
hello again :)

just ran into a small issue, when having query string as template literal spanning multiple lines, can sometimes contain tab `\t` chars depending upon editor formatting. 
for ease of use, can you update the regex to replace all `\t` with spaces to account for this?

otherwise the NetSuite REST API will throw error `[{"detail":"Invalid content in the request body.","o:errorCode":"INVALID_CONTENT"}]`

Thanks

**Comment by ehmad11** [comment]
interesting, I have added another regex to replace all \t with spaces, let me know if it works

**Comment by dylbarne** [comment]
thanks for such a quick turnaround on these! worked like a charm
